#->   Lendo banco de dados

In [ ]:
import pandas as pd

In [ ]:
from os import read
df  = pd.read_csv("dados.csv")

In [ ]:
df.columns

Index(['nu_ano', 'cs_sexo', 'cs_raca', 'sg_uf', 'raiox_tora', 'agravalcoo',
       'agravdiabe', 'agravdoenc', 'bacilosc_e', 'pop_liber', 'pop_rua',
       'pop_imig', 'benef_gov', 'agravdroga', 'agravtabac', 'ano_base', 'cura',
       'pop', 'front', 'tempo_diag_trat_14', 'dt_cul', 'ano_inc_trat',
       'ano_encerra', 'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

In [ ]:
df = df.drop(columns=['nu_ano','ano_inc_trat','sg_uf','dt_cul','ano_base','front'])

In [ ]:
df.shape

(25630, 20)

##• Separação da base em treino e teste (Obrigatório)

In [ ]:
# Selecao treino e teste

In [ ]:
# Separação da base entre variáveis preditoras e desfecho
X = df.drop(columns="cura")
y = df["cura"].copy()

# Separação entre treino (ANO >= 2023) e teste (ANO >= 2023)
X_train = X[X['ano_encerra'] < 2023].drop(columns="ano_encerra").copy()
X_test  = X[X['ano_encerra'] > 2022].drop(columns="ano_encerra").copy()

y_train = y[X['ano_encerra'] < 2023].copy()
y_test  = y[X['ano_encerra'] > 2022].copy()

In [ ]:
print("Proporção das classes no conjunto de TREINO:")
print(y_train.value_counts(normalize=True))

print("\nProporção das classes no conjunto de TESTE:")
print(y_test.value_counts(normalize=True))

Proporção das classes no conjunto de TREINO:
cura
1    0.803671
0    0.196329
Name: proportion, dtype: float64

Proporção das classes no conjunto de TESTE:
cura
1    0.830967
0    0.169033
Name: proportion, dtype: float64

In [ ]:
def visualizar_dataframe(df, nome_df):
  '''Função que dá o shape do dataframe e fornece as 5 primeiras linhas'''

  #Fornece o shape da tabela
  print(f"Shape {nome_df}: ", df.shape)

  #Visualiza as 5 primeiras linhas do DataFrame
  display(df.head())

##• Proporção do desfecho (Obrigatório)

In [ ]:
#Verificação da proporção de abandono na base de treino e teste
display(y_train.value_counts(normalize = True))
display(y_test.value_counts(normalize = True))

cura
1    0.803671
0    0.196329
Name: proportion, dtype: float64

cura
1    0.830967
0    0.169033
Name: proportion, dtype: float64

##• Tratamento de valores ausentes numéricos (Obrigatório)

## Imputação dos Valores Ausentes (Missing Values)

In [ ]:
#Verificação de valores ausentes na base:
print("Quantidade de missings no treino: ", X_train.isna().sum().sum())
print("Quantidade de missings no teste: ", X_test.isna().sum().sum())

Quantidade de missings no treino:  16228
Quantidade de missings no teste:  2996

In [ ]:
#Verificação da proporção de abandono na base de treino e teste
display(X_train.columns)
display(X_test.columns)

Index(['cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo', 'agravdiabe',
       'agravdoenc', 'bacilosc_e', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac', 'pop', 'tempo_diag_trat_14',
       'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

Index(['cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo', 'agravdiabe',
       'agravdoenc', 'bacilosc_e', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac', 'pop', 'tempo_diag_trat_14',
       'escola_faixa', 'contato_5_15', 'faixa_etaria'],
      dtype='object')

In [ ]:
#Lista de variáveis numéricas
lista_variaveis_numericas = ["pop"]

#Lista de variáveis categóricas( tirar pop e cura)
lista_variaveis_categoricas = [ 'cs_sexo', 'cs_raca', 'raiox_tora', 'agravalcoo', 'agravdiabe',
       'agravdoenc', 'bacilosc_e', 'pop_liber', 'pop_rua', 'pop_imig',
       'benef_gov', 'agravdroga', 'agravtabac',
       'tempo_diag_trat_14', 'escola_faixa', 'contato_5_15', 'faixa_etaria']

In [ ]:
#Obtenção das médias na base de treino
median_treino = X_train[lista_variaveis_numericas].median()

#Aplicação das médias na base de treino e de teste
X_train[lista_variaveis_numericas] = X_train[lista_variaveis_numericas].fillna(median_treino)
X_test[lista_variaveis_numericas] = X_test[lista_variaveis_numericas].fillna(median_treino)

##

##• Tratamento de valores ausentes categóricos (Obrigatório)

In [ ]:
#Obtenção da moda nas bases de treino
#modas_treino = X_train[lista_variaveis_categoricas].mode().iloc[0]

#Criaçao de categoria ausente nas base de treino e de teste
X_train[lista_variaveis_categoricas] = X_train[lista_variaveis_categoricas].fillna(9)
X_test[lista_variaveis_categoricas] = X_test[lista_variaveis_categoricas].fillna(9)

In [ ]:
# categoria ausente ja foi criada
#df[lista_variaveis_categoricas].fillna("variavel_ausente", inplace = True)

In [ ]:
#Verificação de valores ausentes na base:
print("Quantidade de missings no treino: ", X_train.isna().sum().sum())
print("Quantidade de missings no teste: ", X_test.isna().sum().sum())

Quantidade de missings no treino:  0
Quantidade de missings no teste:  0

##• Padronização das variáveis numéricas (Obrigatório)

In [ ]:
# Padronizacao de variaveis numericas

In [ ]:
from sklearn.preprocessing import StandardScaler

#Criação do Scaler
standard_scaler = StandardScaler()

#Treino do Scaler na base de treino
standard_scaler.fit(X_train[lista_variaveis_numericas])

StandardScaler()

In [ ]:
# Criação do DataFrame com valores originais e padronizados
df_pop = pd.DataFrame({
    'pop_original': X_train['pop'],
    'pop_padronizada': standard_scaler.transform(X_train[['pop']]).flatten()
})

# Exemplo: salvar em CSV
df_pop.to_csv('pop_padronizada1.csv', index=False)

# Verifique o resultado
print(df_pop.head())

   pop_original  pop_padronizada
0     6211223.0         0.745332
1     6211223.0         0.745332
2     6211223.0         0.745332
3     6211223.0         0.745332
4     6211223.0         0.745332

In [ ]:
#Aplicação do Scaler na base de treino e de teste
X_train[lista_variaveis_numericas] = standard_scaler.transform(X_train[lista_variaveis_numericas])
X_test[lista_variaveis_numericas] = standard_scaler.transform(X_test[lista_variaveis_numericas])

##• Padronização das variáveis One Hot Encoding das categóricas (Obrigatório)

In [ ]:
# One Hot Encoding nas Variáveis Categóricas

In [ ]:
from sklearn.preprocessing import OneHotEncoder

#cria o one hot encoder
one_hot_encoder = OneHotEncoder(drop = "if_binary", sparse_output = False,handle_unknown="ignore")

#treinar o one hot encoding na base de treino
one_hot_encoder.fit(X_train[lista_variaveis_categoricas])

#aplicar na base de treino e de teste
X_train_encoded = pd.DataFrame(one_hot_encoder.transform(X_train[lista_variaveis_categoricas]),
                               columns=one_hot_encoder.get_feature_names_out(),
                               index=X_train.index)

X_test_encoded = pd.DataFrame(one_hot_encoder.transform(X_test[lista_variaveis_categoricas]),
                              columns=one_hot_encoder.get_feature_names_out(),
                              index=X_test.index)

In [ ]:
##Deletando variaveis originais

In [ ]:
#Drop das features categóricas originais
X_train.drop(columns = lista_variaveis_categoricas, inplace = True)
X_test.drop(columns = lista_variaveis_categoricas, inplace = True)

#Junta as variáveis numéricas com as categóricas
X_train = pd.concat([X_train, X_train_encoded], axis=1)
X_test = pd.concat([X_test, X_test_encoded], axis=1)

###Salvando dataframe

In [ ]:
#mount google colab
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Unificando base de Treino
df_train = pd.concat([X_train, y_train], axis = 1)

#Salvando base de Treino
path_to_save_train = "/content/drive/MyDrive/Colab Notebooks/Pasta/nome_arquivo.csv"
df_train.to_csv(path_to_save_train, index = False)

In [ ]:
#Unificando base de Teste
df_test= pd.concat([X_test, y_test], axis = 1)

#Salvando base de Teste
path_to_save_test = "/content/drive/MyDrive/Colab Notebooks/Pasta/nome_arquivo.csv"
df_test.to_csv(path_to_save_test, index = False)